# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# Split DNS: route internal domains to homelab CoreDNS.
# "Restrict to domain" is implicit -- Tailscale never falls back
# to public DNS for split DNS domains.

resource "tailscale_dns_split_nameservers" "lab" {
  domain      = "lab.infiniteroomlabs.cloud"
  nameservers = ["100.86.213.22"]
}

resource "tailscale_dns_split_nameservers" "internal" {
  domain      = "internal.infiniteroomlabs.cloud"
  nameservers = ["100.86.213.22"]
}
